### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by Oliviu27** [googleworkspace/node-samples#203]
When downloading and inserting your credentials.json, the credential's default key is `"web"`.

At startup time this creates a failure because of the following line of code: https://github.com/googleworkspace/node-samples/blob/5b5cce728cb3a9b689abf6de3b6c7612f6940e9b/slides/quickstart/index.js#L43

The suggestion is to update the docs with:
`const {client_secret, client_id, redirect_uris} = credentials.web;`
or alternatively, for the default key of the downloaded JSON to be `installed` rather than `web`. 

I would assume updating the docs accordingly is easier.

**Comment by sqrrrl** [comment]
Quickstart guide + code was recently updated, marking as fixed.
