### ISSUE TITLE
getting random localhost urls with google gmail nodejs quickstart

### ISSUE THREAD

**Issue by theabhayprajapati** [googleworkspace/node-samples#402]
# Summary
![image](https://user-images.githubusercontent.com/88815641/224788313-00e2b76f-6f3d-422c-bea4-ca04e5aa366b.png)

TODO

## Expected Behavior
it should open a static localhost URL for redirect URL if not then recommend something that I  should be doing.
Sample URL: 
Description:
As soon as I `node index.js` it runs the `authorize()` and for authenticating with redirect uris it uses random localhost URLs. what should i do.

## Steps to Reproduce the Problem

1. `git clone && cd gmail/quickstart && yarn `
2. get your `credentials.json`
3. node index.js

**Comment by sqrrrl** [comment]
Did you create the right type of client ID? From the behavior, sounds like you created a web app credential instead of desktop. Desktop apps allow the local callbacks to use ephemeral ports and shouldn't produce that error.

See https://developers.google.com/gmail/api/quickstart/nodejs

**Comment by theabhayprajapati** [comment]
yes i am using googles webapp credentials.
