### ISSUE TITLE
bugs: Failed to get started with gmail Guide

### ISSUE THREAD

**Issue by txp1035** [googleworkspace/node-samples#442]
# Summary

I had an error using the api through the guide linked below
https://developers.google.com/gmail/api/quickstart/nodejs?hl=zh-cn

The sample code is as follows
https://github.com/googleworkspace/node-samples/blob/main/gmail/quickstart/index.js

I tried to search issues but could not find similar issues
I am using Google api for the first time, please help me if you know, thank you very much.

## Expected Behavior

The token information can be obtained normally.

## Actual Behavior

Here's how I do it

https://user-images.githubusercontent.com/9554297/229211740-5f9c8138-e0ab-4b96-9c1a-bcd807b5d6e0.mp4

.

It failed when authenticate was called

Here are some error messages

![image](https://user-images.githubusercontent.com/9554297/229207915-9d347cad-caea-49b7-97cc-8c879e6251da.png)

![image](https://user-images.githubusercontent.com/9554297/229207847-47924b73-31a7-4cd9-87e6-2c742b3cf834.png)

![image](https://user-images.githubusercontent.com/9554297/229212249-b7fff20e-88f8-47ec-9174-03bf23e8d874.png)

## Steps to Reproduce the Problem

Create a new Google Mail and follow the instructions
https://developers.google.com/gmail/api/quickstart/nodejs?hl=zh-cn

**Comment by sqrrrl** [comment]
Can you verify that that URL is reachable from your machine?

```
curl -vv https://oauth2.googleapis.com/token
```

**Comment by txp1035** [comment]
> 您能否验证该 URL 是否可以从您的计算机访问？
> 
> ```
> curl -vv https://oauth2.googleapis.com/token
> ```
I tested it. I can't access it. Is it my network?Do I need to configure anything to access this address? I have opened an agent in China and can access Google normally
![image](https://user-images.githubusercontent.com/9554297/229260299-cd5a71d1-5335-4124-81f0-c5f86a732f86.png)

**Comment by txp1035** [comment]
> 您能否验证该 URL 是否可以从您的计算机访问？
> 
> ```
> curl -vv https://oauth2.googleapis.com/token
> ```

I think it's my terminal network. Thank you

**Comment by txp1035** [comment]
我查询资料

> Can you verify that that URL is reachable from your machine?
> 
> ```
> curl -vv https://oauth2.googleapis.com/token
> ```

I think I found the reason. I turned on the proxy access https request
Does authenticate support proxy configuration?
