### ISSUE TITLE
Node.js Quickstart cannot work

### ISSUE THREAD

**Issue by brillian4616** [googleworkspace/node-samples#96]
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Node version (`node -v`)
  - OS (Mac/Linux/Windows)

**Comment by brillian4616** [comment]
![Capture](https://user-images.githubusercontent.com/67893858/86567754-7496cf80-bf9e-11ea-840b-47d1042a44fc.PNG)

**Comment by brillian4616** [comment]
help please

**Comment by brillian4616** [comment]
??????

**Comment by mr-winson** [comment]
give us an error
